stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: 'production'

# Build job
build_job:
  stage: build
  script:
    - echo "Building the project..."
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

# Test job
test_job:
  stage: test
  script:
    - echo "Running tests..."
    - npm test

# Deploy to QA environment
deploy_to_qa:
  stage: deploy
  script:
    - echo "Deploying to QA environment..."
  only:
    - qa

# Deploy to Production environment
deploy_to_production:
  stage: deploy
  script:
    - echo "Deploying to Production environment..."
  only:
    - master
